# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-19 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('happeningdate', models.DateTimeField()),
                ('smalldescription', models.TextField()),
                ('largedescription', models.TextField()),
                ('imagelink', models.CharField(max_length=500)),
                ('drivelink', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
