# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='largediscription',
            new_name='largedescription',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='smalldiscription',
            new_name='smalldescription',
        ),
    ]
