# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroevents', '0002_auto_20170407_0111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
